DROP DATABASE IF EXISTS xinghanw;
CREATE DATABASE xinghanw;
USE xinghanw;

CREATE TABLE USERAUTH(
	userID INT(11) NOT NULL  PRIMARY KEY AUTO_INCREMENT,
    userName VARCHAR(50) NOT NULL,
    userPassword VARCHAR(100) NOT NULL
);

CREATE TABLE FILE_COLLABORATE(
	file_collaborateID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	fileName VARCHAR(50) NOT NULL,
    ownerName VARCHAR(50) NOT NULL,
    collaboratorName VARCHAR(50) NOT NULL
);

CREATE TABLE FILE_OWNER(
	file_ownerID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fileName VARCHAR(50) NOT NULL,
	ownerName VARCHAR(50) NOT NULL
);

